// This file should be auto-generated by Supabase CLI.
// Running `npx supabase gen types typescript --project-id hkjclbdisriyqsvcpmnp --schema public > src/types/supabase.ts`
// will overwrite this file with the types from your database.
// This placeholder is structured to align with the PawsConnect application's data model.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      dogs: {
        Row: {
          id: string // uuid, primary key
          created_at: string // timestamptz, default now()
          name: string // text, not null
          breed: string // text, not null
          age: number // integer, not null
          gender: "Male" | "Female" | "Unknown" // text, not null
          photos: string[] // _text (array of text), not null
          description: string // text, not null
          health_records: Json // jsonb, not null, stores HealthRecord object from src/types/index.ts
          feeding_schedule: Json // jsonb, not null, stores FeedingSchedule object from src/types/index.ts
          vaccination_records: Json // jsonb, not null, stores VaccinationRecord[] array from src/types/index.ts
          live_stream_url: string | null // text
          status: "Available" | "Pending" | "Adopted" // text, not null, default 'Available'
          location: string // text, not null
          personality_traits: string[] // _text (array of text), not null
        }
        Insert: {
          id?: string // uuid, default gen_random_uuid()
          created_at?: string // timestamptz, default now()
          name: string
          breed: string
          age: number
          gender: "Male" | "Female" | "Unknown"
          photos: string[]
          description: string
          health_records: Json
          feeding_schedule: Json
          vaccination_records: Json
          live_stream_url?: string | null
          status?: "Available" | "Pending" | "Adopted" // default 'Available'
          location: string
          personality_traits: string[]
        }
        Update: {
          id?: string
          created_at?: string
          name?: string
          breed?: string
          age?: number
          gender?: "Male" | "Female" | "Unknown"
          photos?: string[]
          description?: string
          health_records?: Json
          feeding_schedule?: Json
          vaccination_records?: Json
          live_stream_url?: string | null
          status?: "Available" | "Pending" | "Adopted"
          location?: string
          personality_traits?: string[]
        }
        Relationships: []
      }
      user_dog_likes: {
        Row: {
          user_id: string // uuid, FK to auth.users.id
          dog_id: string // uuid, FK to dogs.id
          liked_at: string // timestamptz, default now()
        }
        Insert: {
          user_id: string
          dog_id: string
          liked_at?: string // timestamptz, default now()
        }
        Update: {
          user_id?: string
          dog_id?: string
          liked_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_dog_likes_dog_id_fkey"
            columns: ["dog_id"]
            referencedRelation: "dogs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_dog_likes_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "users" // Supabase specific table
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      gender_enum: "Male" | "Female" | "Unknown"
      dog_status_enum: "Available" | "Pending" | "Adopted"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
